import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "PEUGEOT - LR01",
    description:
      "The LR01 uses the same design as the most iconic bikes from PEUGEOT Cycles' 130-year history and combines it with agile, dynamic performance that's perfectly suited to navigating today's cities.",
    price: 1999.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Bikes",
    rating: 4.8,
    reviews: 124,
    brand: "PEUGEOT",
    material: "Aluminum frame, carbon fork",
    weight: "10.2 kg",
    dimensions: "56 cm frame",
  },
  {
    id: 2,
    name: "PILOT - CHROMOLY 520",
    description: "A versatile road bike with chromoly steel frame for durability and comfort on long rides.",
    price: 999.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Bikes",
    rating: 4.5,
    reviews: 89,
    brand: "PILOT",
    material: "Chromoly steel",
    weight: "11.4 kg",
    dimensions: "54 cm frame",
  },
  {
    id: 3,
    name: "SMITH - Trade Road Helmet",
    description: "Lightweight road cycling helmet with advanced protection and ventilation.",
    price: 120.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "Accessories",
    rating: 4.7,
    reviews: 56,
    brand: "SMITH",
    material: "Polycarbonate shell, EPS foam",
    weight: "280g",
    dimensions: "M/L (55-59cm)",
  },
  {
    id: 4,
    name: "TREK - Domane SL 5",
    description: "Endurance road bike with IsoSpeed decoupler for a smooth ride on rough roads.",
    price: 2499.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Bikes",
    rating: 4.9,
    reviews: 112,
    brand: "TREK",
    material: "Carbon fiber frame and fork",
    weight: "9.7 kg",
    dimensions: "56 cm frame",
  },
  {
    id: 5,
    name: "GIRO - Empire ACC Shoes",
    description: "Classic lace-up road cycling shoes with stiff carbon sole and premium fit.",
    price: 299.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Shoes",
    rating: 4.6,
    reviews: 78,
    brand: "GIRO",
    material: "Microfiber upper, carbon sole",
    weight: "215g (size 42)",
    dimensions: "Available in sizes 39-47",
  },
  {
    id: 6,
    name: "CASTELLI - Perfetto RoS Jacket",
    description: "All-weather cycling jacket with Rain or Shine (RoS) technology for versatile protection.",
    price: 229.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Clothing",
    rating: 4.8,
    reviews: 93,
    brand: "CASTELLI",
    material: "GORE-TEX INFINIUM™ fabric",
    weight: "305g (size M)",
    dimensions: "Available in sizes S-XXL",
  },
  {
    id: 7,
    name: "GARMIN - Edge 530",
    description: "Advanced GPS cycling computer with performance insights and navigation features.",
    price: 299.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Accessories",
    rating: 4.7,
    reviews: 105,
    brand: "GARMIN",
    material: "Plastic, glass screen",
    weight: "75g",
    dimensions: "2.0 x 3.2 x 0.8 inches",
  },
  {
    id: 8,
    name: "SPECIALIZED - S-Works Prevail II",
    description: "Ultra-lightweight helmet with advanced aerodynamics and cooling system.",
    price: 249.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Accessories",
    rating: 4.9,
    reviews: 67,
    brand: "SPECIALIZED",
    material: "Carbon fiber reinforced skeleton",
    weight: "200g",
    dimensions: "S/M/L sizes available",
  },
  {
    id: 9,
    name: "OAKLEY - Sutro Sunglasses",
    description: "Sport performance sunglasses with enhanced coverage and Prizm lens technology.",
    price: 169.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Accessories",
    rating: 4.6,
    reviews: 82,
    brand: "OAKLEY",
    material: "O Matter frame, Prizm lenses",
    weight: "32g",
    dimensions: "One size fits most",
  },
  {
    id: 10,
    name: "RAPHA - Pro Team Bib Shorts",
    description: "High-performance cycling bib shorts with supportive chamois for long rides.",
    price: 275.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "Clothing",
    rating: 4.8,
    reviews: 91,
    brand: "RAPHA",
    material: "78% nylon, 22% elastane",
    weight: "180g",
    dimensions: "XS-XXL sizes available",
  },
  {
    id: 11,
    name: "WAHOO - ELEMNT BOLT",
    description: "Aerodynamic GPS bike computer with smart navigation and workout tracking.",
    price: 229.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Accessories",
    rating: 4.7,
    reviews: 88,
    brand: "WAHOO",
    material: "Plastic housing",
    weight: "68g",
    dimensions: "2.4 x 1.9 x 0.8 inches",
  },
  {
    id: 12,
    name: "SHIMANO - RC9 S-PHYRE",
    description: "Premium road cycling shoes with carbon sole and BOA fit system.",
    price: 425.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "Shoes",
    rating: 4.9,
    reviews: 76,
    brand: "SHIMANO",
    material: "Synthetic leather, carbon composite sole",
    weight: "235g (size 42)",
    dimensions: "Sizes 38-48 available",
  },
]
